#!/usr/bin/env zsh

choices=(
  "cbonsai -S"
  "asciiquarium"
  "cmatrix"
  "pipes.sh"
)

local last_file="$HOME/.tsaver-last"
local last=""
[[ -f $last_file ]] && last=$(<"$last_file")

integer idx
while true; do
  idx=$((RANDOM % ${#choices[@]} + 1))
  [[ "$idx" != "$last" ]] && break
done

echo "$idx" > "$last_file"
eval ${choices[$idx]}
